In [2]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/smoke/train.csv")

df

,성별코드,연령대코드(5세단위),신장(5Cm단위),체중(5Kg단위),허리둘레,시력(좌),시력(우),청력(좌),청력(우),수축기혈압,...,혈색소,요단백,혈청크레아티닌,(혈청지오티)AST,(혈청지오티)ALT,감마지티피,흡연상태,구강검진수검여부,치아우식증유무,치석
0,F,55,145,55,73.0,0.7,0.5,1.0,1.0,129.0,...,12.9,1.0,0.9,172.0,209.0,15.0,0,Y,0.0,Y
1,M,40,180,55,74.0,1.5,1.5,1.0,1.0,102.0,...,15.6,1.0,0.8,30.0,19.0,23.0,1,Y,0.0,Y
2,F,55,150,50,72.0,1.0,0.2,1.0,1.0,116.0,...,14.1,1.0,1.0,31.0,19.0,10.0,0,Y,0.0,N
3,M,40,170,85,89.0,1.0,0.8,1.0,1.0,124.0,...,16.7,1.0,1.0,26.0,38.0,108.0,1,Y,1.0,Y
4,F,40,155,45,62.0,0.5,1.0,1.0,1.0,127.0,...,12.9,1.0,0.7,20.0,11.0,13.0,0,Y,0.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44548,F,60,145,50,87.0,1.0,1.0,1.0,1.0,140.0,...,12.3,1.0,0.5,24.0,32.0,15.0,0,Y,1.0,Y
44549,M,40,175,75,88.0,1.5,1.2,1.0,1.0,139.0,...,15.3,1.0,0.8,62.0,106.0,49.0,1,Y,0.0,Y
44550,F,60,150,55,82.0,0.9,0.9,1.0,1.0,124.0,...,14.1,1.0,0.5,38.0,34.0,26.0,0,Y,0.0,Y
44551,M,40,170,50,69.0,0.4,1.2,1.0,1.0,117.0,...,14.2,1.0,0.9,22.0,17.0,55.0,1,Y,0.0,N
44552,F,40,155,50,72.5,1.0,1.0,1.0,1.0,109.0,...,11.7,1.0,0.6,16.0,10.0,7.0,0,Y,0.0,N

In [3]:
# Q1. 시력(좌) 와 시력(우)의 값이 같은 남성의 허리둘레의 평균은?

df.loc[(df['시력(좌)'] == df['시력(우)']) & (df['성별코드']=='M')]['허리둘레'].mean()

84.9768266281797

In [8]:
# Q2. 40대(연령대코드 40,45) 여성 중 '총콜레스테롤'값이 40대 여성의 '총콜레스테롤' 

# 중간값 이상을  가지는 그룹과 50대(연령대코드 50,55) 여성 중 '총콜레스테롤'값이 50대 여성의 '총콜레스테롤' 중간값 이상을 가지는 두 그룹의 '수축기혈압'이 독립성,정규성,등분산성이 만족하는것을 확인했다. 

# 두 그룹의 '수축기혈압'의 독립표본 t 검증 결과를 통계값, p-value 구분지어 구하여라.

f1 = df.loc[(df['성별코드']=='F') & (df['연령대코드(5세단위)'].isin([50,55]))]
f2 = df.loc[(df['성별코드']=='F') & (df['연령대코드(5세단위)'].isin([40,45]))]

f1f = f1.loc[f1['총콜레스테롤'] >= f1['총콜레스테롤'].median()]['수축기혈압']
f2f = f2.loc[f2['총콜레스테롤'] >= f2['총콜레스테롤'].median()]['수축기혈압']

import scipy.stats

print(scipy.stats.ttest_ind(f1f, f2f, equal_var=True)[0])
print(scipy.stats.ttest_ind(f1f, f2f, equal_var=True)[1])

8.954384087520708
4.399762427897212e-19

## 2유형

In [10]:
trainData  = 'https://raw.githubusercontent.com/Datamanim/datarepo/main/smoke/train.csv'
testData  = 'https://raw.githubusercontent.com/Datamanim/datarepo/main/smoke/test.csv'
subData  = 'https://raw.githubusercontent.com/Datamanim/datarepo/main/smoke/submission.csv'

import pandas as pd

train = pd.read_csv(trainData)
test = pd.read_csv(testData)
submission = pd.read_csv(subData)


train.head()

,성별코드,연령대코드(5세단위),신장(5Cm단위),체중(5Kg단위),허리둘레,시력(좌),시력(우),청력(좌),청력(우),수축기혈압,...,혈색소,요단백,혈청크레아티닌,(혈청지오티)AST,(혈청지오티)ALT,감마지티피,흡연상태,구강검진수검여부,치아우식증유무,치석
0,F,55,145,55,73.0,0.7,0.5,1.0,1.0,129.0,...,12.9,1.0,0.9,172.0,209.0,15.0,0,Y,0.0,Y
1,M,40,180,55,74.0,1.5,1.5,1.0,1.0,102.0,...,15.6,1.0,0.8,30.0,19.0,23.0,1,Y,0.0,Y
2,F,55,150,50,72.0,1.0,0.2,1.0,1.0,116.0,...,14.1,1.0,1.0,31.0,19.0,10.0,0,Y,0.0,N
3,M,40,170,85,89.0,1.0,0.8,1.0,1.0,124.0,...,16.7,1.0,1.0,26.0,38.0,108.0,1,Y,1.0,Y
4,F,40,155,45,62.0,0.5,1.0,1.0,1.0,127.0,...,12.9,1.0,0.7,20.0,11.0,13.0,0,Y,0.0,N

In [11]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44553 entries, 0 to 44552
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   성별코드         44553 non-null  object
 1   연령대코드(5세단위)  44553 non-null  int64
 2   신장(5Cm단위)    44553 non-null  int64
 3   체중(5Kg단위)    44553 non-null  int64
 4   허리둘레         44553 non-null  float64
 5   시력(좌)        44553 non-null  float64
 6   시력(우)        44553 non-null  float64
 7   청력(좌)        44553 non-null  float64
 8   청력(우)        44553 non-null  float64
 9   수축기혈압        44553 non-null  float64
 10  이완기혈압        44553 non-null  float64
 11  식전혈당(공복혈당)   44553 non-null  float64
 12  총콜레스테롤       44553 non-null  float64
 13  트리글리세라이드     44553 non-null  float64
 14  HDL콜레스테롤     44553 non-null  float64
 15  LDL콜레스테롤     44553 non-null  float64
 16  혈색소          44553 non-null  float64
 17  요단백          44553 non-null  float64
 18  혈청크레아티닌      44553 non-null  float64
 19  (혈청지오티)AST   44553 non-null  float64
 20  (혈청지오티)ALT   44553 non-null  float64
 21  감마지티피        44553 non-null  float64
 22  흡연상태         44553 non-null  int64
 23  구강검진수검여부     44553 non-null  object
 24  치아우식증유무      44553 non-null  float64
 25  치석           44553 non-null  object
dtypes: float64(19), int64(4), object(3)
memory usage: 8.8+ MB

In [12]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier


def preprocessing(df, target='train', encoderLst=None):

    drop_col = ['구강검진수검여부']

    df = df.drop(drop_col, axis=1)


    df = pd.get_dummies(df)

    if target == 'train':
        scaler = MinMaxScaler()
        df = scaler.fit_transform(df)

        encoderLst = [scaler]
        return df, encoderLst

    elif target == 'test':
        scaler = encoderLst[0]

        df = scaler.fit_transform(df)
        return df

    return None

X = train.drop(['흡연상태'], axis=1)
y = train['흡연상태']


preprocessingdf, encoderLst = preprocessing(X)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(preprocessingdf, y, test_size=0.33, random_state=42)

rf = RandomForestClassifier()

rf.fit(X_train,y_train)

y_pred = rf.predict(X_test)

from sklearn.metrics import f1_score

f1_score(y_test, y_pred)

0.6697116245746015

In [13]:
preprocessing_test_df = preprocessing(test, 'test', encoderLst)

test_pred = rf.predict(preprocessing_test_df)

print(test_pred)

[0 0 1 ... 0 0 0]

## 1유형

In [16]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/smoke/train.csv")
df.head()

,성별코드,연령대코드(5세단위),신장(5Cm단위),체중(5Kg단위),허리둘레,시력(좌),시력(우),청력(좌),청력(우),수축기혈압,...,혈색소,요단백,혈청크레아티닌,(혈청지오티)AST,(혈청지오티)ALT,감마지티피,흡연상태,구강검진수검여부,치아우식증유무,치석
0,F,55,145,55,73.0,0.7,0.5,1.0,1.0,129.0,...,12.9,1.0,0.9,172.0,209.0,15.0,0,Y,0.0,Y
1,M,40,180,55,74.0,1.5,1.5,1.0,1.0,102.0,...,15.6,1.0,0.8,30.0,19.0,23.0,1,Y,0.0,Y
2,F,55,150,50,72.0,1.0,0.2,1.0,1.0,116.0,...,14.1,1.0,1.0,31.0,19.0,10.0,0,Y,0.0,N
3,M,40,170,85,89.0,1.0,0.8,1.0,1.0,124.0,...,16.7,1.0,1.0,26.0,38.0,108.0,1,Y,1.0,Y
4,F,40,155,45,62.0,0.5,1.0,1.0,1.0,127.0,...,12.9,1.0,0.7,20.0,11.0,13.0,0,Y,0.0,N

In [21]:
# Q1. 수축기혈압과 이완기 혈압기 수치의 차이를 새로운 컬럼('혈압차') 으로 생성하고, 연령대 코드별 각 그룹 중 '혈압차' 의 분산이 5번째로 큰 연령대 코드를 구하여라

df['혈압차'] = df['수축기혈압']-df['이완기혈압']
df.groupby('연령대코드(5세단위)')['혈압차'].var().sort_values(ascending=False)

연령대코드(5세단위)
80    154.537248
70    115.999711
75    115.471623
65     99.635384
60     94.386922
85     86.263736
55     79.294182
45     71.445083
50     71.207529
25     68.794878
40     67.285468
20     66.555720
30     61.990014
35     60.757553
Name: 혈압차, dtype: float64

In [22]:
# Q2. 비만도를 나타내는 지표인 WHtR는 허리둘레 / 키로 표현한다. 일반적으로 0.58이상이면 비만으로 분류한다. 데이터중 WHtR 지표상 비만인 인원의 남/여 비율을 구하여라

df['비만'] = df['허리둘레']/df['신장(5Cm단위)']

data = df.loc[df['비만']>=0.58].성별코드.value_counts()

data['M']/data['F']

1.1693877551020408

## 2유형

In [23]:
trainData  = 'https://raw.githubusercontent.com/Datamanim/datarepo/main/insurance/train.csv'
testData  = 'https://raw.githubusercontent.com/Datamanim/datarepo/main/insurance/test.csv'
subData  = 'https://raw.githubusercontent.com/Datamanim/datarepo/main/insurance/submission.csv'

In [24]:
#데이터로드
import pandas as pd

train = pd.read_csv(trainData,index_col=0)
test = pd.read_csv(testData,index_col=0)
submission = pd.read_csv(subData,index_col=0)

train.head()

,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
id,,,,,,,,,,,
188957,Female,25,1,17.0,1,< 1 Year,No,38785.0,152.0,59,0
275631,Male,20,1,22.0,0,< 1 Year,No,2630.0,160.0,113,0
329036,Female,40,1,41.0,0,1-2 Year,Yes,33165.0,124.0,188,0
227288,Female,28,1,30.0,1,< 1 Year,No,29038.0,152.0,233,0
300441,Female,50,1,28.0,0,1-2 Year,Yes,31325.0,124.0,258,0

In [25]:
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split

X = train.drop('Response', axis=1)
y = train['Response']

X = pd.get_dummies(X)

train_col = list(X.columns)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42, stratify = y)

rf = RandomForestClassifier(random_state=42)

rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)


from sklearn.metrics import f1_score

f1_score(y_test, y_pred)

0.17844047910046446

In [26]:
test = pd.get_dummies(test)
test = test[train_col]

test_pred = rf.predict(test)

print(test_pred)

[0 0 0 ... 0 0 0]